const Head = () => (
  <>
    <title>Hi-Timer</title>
    <link
      rel="preload"
      href="/api/record/read?event=3x3x3&limit=100"
      as="fetch"
      crossOrigin="anonymous"
    />
    <meta name="description" content="Generated by create next app" />
    <meta charSet="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
  </>
);
export default Head;
