const Head = () => (
  <>
    <title>Hi-Timer dayo</title>
    <meta name="description" content="Generated by create next app" />
    <meta charSet="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
  </>
);
export default Head;
